### ISSUE TITLE
간략한 테스트 전수조사 후 생각되는 문제점

### ISSUE THREAD

**Issue by alls7554** [ksu-ecole/soccer-server#16]
현재 문제라고 생각되는 점

1. 회원정보 조회는 자신의 정보 밖에 조회 하지 못한다.
	A로 로그인하여 B의 정보를 조회하지 못함
	추가 api를 제작하여 일부정보를 조회할 수 있는 api필요

2. 팀에 가입시 ("/{accountId}/join/{teamId}") 순환 참조 발생
	이유는 Team.java에 있는 ownerId (현재 @JsonIgnore로 대처, 필요시 Dto로 변경)
	팀 조회시 팀의 주장을 알 수가 없어서 Dto로 변경해야할거 같다는 생각이 듭니다.

**Comment by yks095** [comment]
이번 주 금요일 목표가 요청 및 응답을 DTO로 모두 변경하고, API 접근 권한 및 대부분의 기능을 마무리하는 것이 목표입니다.
다음주까지는 여러 버그 수정 및 리팩토링을 진행할 예정입니다.

**Comment by alls7554** [comment]
앗 까먹을까봐 기록으로 남겨놨는데 알려주셔서 감사합니다 이번 주 금요일에 뵙겠습니다!!!
